name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
  
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
          
    - name: Restore Solution
      run: dotnet restore GitTracker.sln
      
    - name: Build Solution
      run: dotnet build GitTracker.sln --configuration Release
      
    - name: Test Solution
      run: dotnet test GitTracker.sln --configuration Release
      
    - name: Publish GitTracker
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: GitTracker/GitTracker.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
